project_id = "shindkpwyxpsexhhfsyg"

[functions.repository-api]
verify_jwt = false

[functions.ai-chat]
verify_jwt = true

[functions.code-analyzer]
verify_jwt = true

[functions.google-drive-backup]
verify_jwt = true

[functions.backup-scheduler]
verify_jwt = false